import * as dotenv from 'dotenv';

dotenv.config();

/* Replicate credentials for config */
const REPLICATE_AUTH_TOKEN = process.env.REPLICATE_AUTH_TOKEN;
const REPLICATE_MODEL_VERSION = process.env.REPLICATE_MODEL_VERSION;
const REPLICATE_CONTROL_NET_VERSION = process.env.REPLICATE_CONTROL_NET_VERSION;
const REPLICATE_UPSCALE_MODEL_VERSION = process.env.REPLICATE_UPSCALE_MODEL_VERSION;
const REPLICATE_URL = process.env.REPLICATE_URL;
const REPLICATE_NEGATIVE_PROMPT = process.env.REPLICATE_NEGATIVE_PROMPT;
const REPLICATE_VARIATION_STRONG: Record<string, number> = process.env.REPLICATE_VARIATION_STRONG
  ? JSON.parse(process.env.REPLICATE_VARIATION_STRONG)
  : { promptGuidance: 6, imageGuidance: 0.8 };
const REPLICATE_VARIATION_SUBTLE: Record<string, number> = process.env.REPLICATE_VARIATION_SUBTLE
  ? JSON.parse(process.env.REPLICATE_VARIATION_SUBTLE)
  : { promptGuidance: 10, imageGuidance: 0.5 };
const REPLICATE_IMAGE_SIZE: Record<string, number> = process.env.REPLICATE_IMAGE_SIZE
  ? JSON.parse(process.env.REPLICATE_IMAGE_SIZE)
  : { width: 512, height: 512 };

/* Cloudinary credentials for config */
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

/* Credit System Service */
const CREDIT_SYSTEM_SERVICE_BASE_URL = process.env.CREDIT_SYSTEM_SERVICE_BASE_URL;
const MINIMUM_CREDIT_PURCHASE_AMOUNT = +process.env.MINIMUM_CREDIT_PURCHASE_AMOUNT || 0.01;
const SPC_TO_CREDIT_CONVERSION_RATE = +process.env.SPC_TO_CREDIT_CONVERSION_RATE || 1;
const ENABLE_ART_GENERATION_CREDIT_CONSUMPTION = process.env.ENABLE_ART_GENERATION_CREDIT_CONSUMPTION === 'true';
const PROMPT_GENERATION_CREDIT_COST = +process.env.PROMPT_GENERATION_CREDIT_COST || 1;
const ENABLE_DAILY_CREDITS = process.env.ENABLE_DAILY_CREDITS === 'true';
const DEFAULT_USER_CREDIT_BALANCE = +process.env.DEFAULT_USER_CREDIT_BALANCE || 30;
const OPEN_AI_PROMPT_CREDIT_COST = +process.env.OPEN_AI_PROMPT_CREDIT_COST || 10;
const BASIC_USER_FREE_CREDIT_LIMIT = +process.env.BASIC_USER_FREE_CREDIT_LIMIT || 20;
const VERIFIED_ARTIST_FREE_CREDIT_LIMIT = +process.env.VERIFIED_ARTIST_FREE_CREDIT_LIMIT || 150;
const VERIFIED_USER_FREE_CREDIT_LIMIT = +process.env.VERIFIED_USER_FREE_CREDIT_LIMIT || 40;
const VERIFIED_COLLECTOR_FREE_CREDIT_LIMIT = +process.env.VERIFIED_COLLECTOR_FREE_CREDIT_LIMIT || 250;
const UPGRADED_GUEST_USER_CREDIT_AMOUNT = +process.env.UPGRADED_GUEST_USER_CREDIT_AMOUNT || 20;
const ENABLE_TIER_LEVEL_ART_GENERATION = process.env.ENABLE_TIER_LEVEL_ART_GENERATION === 'true';
const VERIFIED_USER_UPGRADE_REWARD = +process.env.VERIFIED_USER_UPGRADE_REWARD || 40;

/* Gorse credentials for use with gorse service */
const GORSE_SERVICE_DOMAIN = process.env.GORSE_SERVICE_DOMAIN;
const GORSE_SERVER_API_KEY = process.env.GORSE_SERVER_API_KEY;

/* Dreambooth credentials for config */
const DREAMBOOTH_AUTH_TOKEN = process.env.DREAMBOOTH_AUTH_TOKEN || '';
const DREAMBOOTH_TRAINING_URL = process.env.DREAMBOOTH_TRAINING_URL || '';
const DREAMBOOTH_TRAINER_VERSION = process.env.DREAMBOOTH_TRAINER_VERSION || '';
const DREAMBOOTH_CLASS_PROMPT = process.env.DREAMBOOTH_CLASS_PROMPT || 'a photo of me';
const DREAMBOOTH_WEBHOOK_SECRET = process.env.DREAMBOOTH_WEBHOOK_SECRET || '';
const DREAMBOOTH_PREDICTION_URL = process.env.DREAMBOOTH_PREDICTION_URL || '';
const DREAMBOOTH_USERNAME = process.env.DREAMBOOTH_USERNAME || '';
const DREAMBOOTH_NEGATIVE_PROMPT =
  process.env.DREAMBOOTH_NEGATIVE_PROMPT || 'out of frame, duplicate, watermark, signature, text';
const DREAMBOOTH_PROMPT_DETAILS = process.env.DREAMBOOTH_PROMPT_DETAILS
  ? process.env.DREAMBOOTH_PROMPT_DETAILS.split(',')
  : [];
const DREAMBOOTH_PROMPT_STYLES = process.env.DREAMBOOTH_PROMPT_STYLES
  ? process.env.DREAMBOOTH_PROMPT_STYLES.split(',')
  : [];
const DREAMBOOTH_PROMPT_CONTENT = process.env.DREAMBOOTH_PROMPT_CONTENT
  ? process.env.DREAMBOOTH_PROMPT_CONTENT.split(',')
  : [];
const DREAMBOOTH_TRAINING_STEPS_PER_IMAGE = +process.env.DREAMBOOTH_TRAINING_STEPS_PER_IMAGE || 100;
const DREAMBOOTH_AVATAR_PROMPT = process.env.DREAMBOOTH_AVATAR_PROMPT || 'a portrait of {model},';
const DREAMBOOTH_TRAINING_CREDIT_COST = +process.env.DREAMBOOTH_TRAINING_CREDIT_COST || 300;
const REPLICATE_WEBHOOK_SECRET = process.env.REPLICATE_WEBHOOK_SECRET || '';
const DREAMBOOTH_MODEL_DESTINATION = process.env.DREAMBOOTH_MODEL_DESTINATION || '';
const DREAMBOOTH_FACE_DETECTION_ENABLED = process.env.DREAMBOOTH_FACE_DETECTION_ENABLED === 'true';
const DREAMBOOTH_FINE_TUNE_MODEL_OWNER = process.env.DREAMBOOTH_FINE_TUNE_MODEL_OWNER || '';
const DREAMBOOTH_FINE_TUNE_MODEL_NAME = process.env.DREAMBOOTH_FINE_TUNE_MODEL_NAME || '';
const DREAMBOOTH_FINE_TUNE_MODEL_VERSION = process.env.DREAMBOOTH_FINE_TUNE_MODEL_VERSION || '';
const DREAMBOOTH_IMAGE_DIMENSIONS: Record<string, number> = process.env.DREAMBOOTH_IMAGE_DIMENSIONS
  ? JSON.parse(process.env.DREAMBOOTH_IMAGE_DIMENSIONS)
  : { width: 896, height: 640 };
const DREAMBOOTH_LORA_ENABLED = process.env.DREAMBOOTH_LORA_ENABLED === 'true';

/* Buyback credentials for config */
const ENABLE_BUYBACK_V2 = process.env.ENABLE_BUYBACK_V2 === 'true';
const ENABLE_BUYBACK_V2_BADGECOUNTER = process.env.ENABLE_BUYBACK_V2_BADGECOUNTER === 'true';

/* Styles */
const ENABLE_TRENDING_PUBLIC_STYLES = process.env.ENABLE_TRENDING_PUBLIC_STYLES === 'true';
const TRENDING_STYLES_DAY_COUNT = +process.env.TRENDING_STYLES_DAY_COUNT || 7;
const ENABLE_DEFAULT_STYLES = process.env.ENABLE_DEFAULT_STYLES === 'true';
const STYLES_PREVIEW_IMAGE_CACHE_DURATION_IN_SECONDS =
  +process.env.STYLES_PREVIEW_IMAGE_CACHE_DURATION_IN_SECONDS || 14400;
const ENABLE_STYLES_DESCRIPTORS_WEIGHTS = process.env.ENABLE_STYLES_DESCRIPTORS_WEIGHTS === 'true';
const ENABLE_UPDATE_STYLE_WITH_SWANLINGS = process.env.ENABLE_UPDATE_STYLE_WITH_SWANLINGS === 'true';
const DEFAULT_STYLE_PREVIEW_IMAGE_URL = process.env.DEFAULT_STYLE_PREVIEW_IMAGE_URL || '';
const ENABLE_PINNED_STYLES = process.env.ENABLE_PINNED_STYLES === 'true';
const ENABLE_TRENDING_STYLES_OPTIMIZATION = process.env.ENABLE_TRENDING_STYLES_OPTIMIZATION === 'true';
const POPULAR_STYLES_DAY_COUNT = +process.env.POPULAR_STYLES_DAY_COUNT || 30;

/* Community Models */
const PRIVATE_MODELS_ENABLED = process.env.PRIVATE_MODELS_ENABLED === 'true';
const ENABLE_ASPECT_RATIO = process.env.ENABLE_ASPECT_RATIO === 'true';

/* User Settings */
const ENABLE_SWANLING_DISPLAY_SETTINGS = process.env.ENABLE_SWANLING_DISPLAY_SETTINGS === 'true';
const ENABLE_DAILY_SPC = process.env.ENABLE_DAILY_SPC === 'true';
const ENABLE_SWAN_TRADING = process.env.ENABLE_SWAN_TRADING === 'true';

/* Energy System */
const ENERGY_SYSTEM_ENABLED = process.env.ENERGY_SYSTEM_ENABLED === 'true';
const BASIC_USER_ENERGY_REFILL_GAP_IN_HOURS = +process.env.BASIC_USER_ENERGY_REFILL_GAP_IN_HOURS || 6;
const VERIFIED_USER_ENERGY_REFILL_GAP_IN_HOURS = +process.env.VERIFIED_USER_ENERGY_REFILL_GAP_IN_HOURS || 6;
const BASIC_USER_ENERGY_REFILL_AMOUNT = +process.env.BASIC_USER_ENERGY_REFILL_AMOUNT || 1;
const VERIFIED_USER_ENERGY_REFILL_AMOUNT = +process.env.VERIFIED_USER_ENERGY_REFILL_AMOUNT || 2;
const BASIC_USER_INITIAL_ENERGY = +process.env.BASIC_USER_INITIAL_ENERGY || 1;
const VERIFIED_USER_INITIAL_ENERGY = +process.env.VERIFIED_USER_INITIAL_ENERGY || 2;
const BASIC_USER_ENERGY_CAP = +process.env.BASIC_USER_ENERGY_CAP || 5;
const VERIFIED_USER_ENERGY_CAP = +process.env.VERIFIED_USER_ENERGY_CAP || 10;
const ENERGY_COST_PER_SWANLING = +process.env.ENERGY_COST_PER_SWANLING || 1;
const VERIFIED_ARTIST_INITIAL_ENERGY = +process.env.VERIFIED_ARTIST_INITIAL_ENERGY || 3;
const VERIFIED_ARTIST_ENERGY_CAP = +process.env.VERIFIED_ARTIST_ENERGY_CAP || 15;
const VERIFIED_ARTIST_ENERGY_REFILL_GAP_IN_HOURS = +process.env.VERIFIED_ARTIST_ENERGY_REFILL_GAP_IN_HOURS || 6;
const VERIFIED_ARTIST_ENERGY_REFILL_AMOUNT = +process.env.VERIFIED_ARTIST_ENERGY_REFILL_AMOUNT || 3;
const VERIFIED_COLLECTOR_AESTHETE_INITIAL_ENERGY = +process.env.VERIFIED_COLLECTOR_AESTHETE_INITIAL_ENERGY || 3;
const VERIFIED_COLLECTOR_AESTHETE_ENERGY_CAP = +process.env.VERIFIED_COLLECTOR_AESTHETE_ENERGY_CAP || 15;
const VERIFIED_COLLECTOR_AESTHETE_ENERGY_REFILL_GAP_IN_HOURS =
  +process.env.VERIFIED_COLLECTOR_AESTHETE_ENERGY_REFILL_GAP_IN_HOURS || 6;
const VERIFIED_COLLECTOR_AESTHETE_ENERGY_REFILL_AMOUNT =
  +process.env.VERIFIED_COLLECTOR_AESTHETE_ENERGY_REFILL_AMOUNT || 3;

/* Chat Service */
const CHAT_SERVICE_BASE_URL = process.env.CHAT_SERVICE_BASE_URL || '';
const CHAT_SERVICE_CLIENT_ID = process.env.CHAT_SERVICE_CLIENT_ID || '';
const CHAT_SERVICE_CLIENT_API_KEY = process.env.CHAT_SERVICE_CLIENT_API_KEY || '';
const ENABLE_REDIS_PUBSUB = process.env.ENABLE_REDIS_PUBSUB === 'true';

/* Onfido */
const ONFIDO_TOKEN = process.env.ONFIDO_TOKEN || '';
const ONFIDO_URL = process.env.ONFIDO_URL || '';
const ONFIDO_WORKFLOW_ID = process.env.ONFIDO_WORKFLOW_ID || '';
const GOOGLE_SHEETS_UPDATE_ENABLED = process.env.GOOGLE_SHEETS_UPDATE_ENABLED === 'true';
const GOOGLE_SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || '';
const GOOGLE_PRIVATE_KEY = process.env.GOOGLE_PRIVATE_KEY || '';
const BOUNTY_WINNERS_GOOGLE_SHEET_ID = process.env.BOUNTY_WINNERS_GOOGLE_SHEET_ID || '';
const BOUNTY_ENTRIES_GOOGLE_SHEET_ID = process.env.BOUNTY_ENTRIES_GOOGLE_SHEET_ID || '';
const SUBSCRIBERS_GOOGLE_SHEET_ID = process.env.SUBSCRIBERS_GOOGLE_SHEET_ID || '';
const TRANSACTION_QUEUE_ENABLED = process.env.TRANSACTION_QUEUE_ENABLED === 'true';

/* Achievements 2.0 */
const ACHIEVEMENTS_V2_ENABLED = process.env.ACHIEVEMENTS_V2_ENABLED === 'true';
const ACHIEVEMENT_NOTIFICATION_ICON_URL = process.env.ACHIEVEMENT_NOTIFICATION_ICON_URL || '';
const SPLURGE_ART_ID = process.env.SPLURGE_ART_ID || '';
const VERIFIED_USER_BADGE_URL = process.env.VERIFIED_USER_BADGE_URL || '';
const VERIFIED_ARTIST_BADGE_URL = process.env.VERIFIED_ARTIST_BADGE_URL || '';
const VERIFIED_AESTHETE_BADGE_URL = process.env.VERIFIED_AESTHETE_BADGE_URL || '';
const VERIFIED_COLLECTOR_BADGE_URL = process.env.VERIFIED_COLLECTOR_BADGE_URL || '';

/* Open-AI */
const OPEN_AI_API_KEY = process.env.OPEN_AI_API_KEY || '';
const PREMIUM_MODELS: string[] = process.env.PREMIUM_MODELS
  ? process.env.PREMIUM_MODELS.replace(/'/g, '"')
      .slice(1, -1)
      .split(',')
      .map((value) => value.trim().replace(/"/g, ''))
  : [];
const GPT_4_VISION_PREVIEW_MAX_TOKENS = +process.env.GPT_4_VISION_PREVIEW_MAX_TOKENS || 4096;
const OPEN_AI_IMAGE_VISION_MODEL = process.env.OPEN_AI_IMAGE_VISION_MODEL || '';

/** Notification Service */
const NOTIFICATION_SERVICE_BASE_URL = process.env.NOTIFICATION_SERVICE_BASE_URL || '';

/* User Service */
const REQUIRED_BOUNTIES_WON = +process.env.REQUIRED_BOUNTIES_WON || 10;
const REQUIRED_CREATION_VALUE = +process.env.REQUIRED_CREATION_VALUE || 1000;
const REQUIRED_BOUNTY_RANK = +process.env.REQUIRED_BOUNTY_RANK || 10;
const REQUIRED_BOUNTY_HOSTED_DATE = process.env.REQUIRED_BOUNTY_HOSTED_DATE || '2023-10-01T00:00:00.000Z';
const REQUIRED_LAST_MOMENT_CREATION_DAYS = +process.env.REQUIRED_LAST_MOMENT_CREATION_DAYS || 30;
const USER_SERVICE_BASE_URL = process.env.USER_SERVICE_BASE_URL || '';
const TOP_UP_ICON_URL = process.env.TOP_UP_ICON_URL || '';
const SPC_TO_USD_CONVERSION_RATE = process.env.SPC_TO_USD_CONVERSION_RATE || '1:1';
const MIN_SPC_PAYOUT = +process.env.MIN_SPC_PAYOUT_AMOUNT || 6000;
const MAX_SPC_PAYOUT = +process.env.MAX_SPC_PAYOUT_AMOUNT || 30000;
const PAYOUT_CYCLE_PROCESSING_DATE = +process.env.PAYOUT_CYCLE_PROCESSING_DATE || 16;
const PAYOUT_ICON_URL = process.env.PAYOUT_ICON_URL || '';
const ENABLE_PAYOUT_NOTIFICATION = process.env.ENABLE_PAYOUT_NOTIFICATION === 'true';
const SWAN_VALUE_MAXIMUM_THRESHOLD = +process.env.SWAN_VALUE_MAXIMUM_THRESHOLD || 1.3;
const SWAN_VALUE_MINIMUM_THRESHOLD = +process.env.SWAN_VALUE_MINIMUM_THRESHOLD || 0.7;
const ENABLE_DAILY_SUBSCRIPTION_VALIDATION = process.env.ENABLE_DAILY_SUBSCRIPTION_VALIDATION === 'true';

/** Art Generation */
const MAXIMUM_ART_GENERATION_REQUESTS_IN_PROGRESS = +process.env.MAXIMUM_ART_GENERATION_REQUESTS_IN_PROGRESS || 3;
const ENABLE_MAX_ART_GENERATION_LIMIT = process.env.ENABLE_MAX_ART_GENERATION_LIMIT === 'true';
const ENABLE_TIER_LEVEL_PREMIUM_MODEL_USAGE = process.env.ENABLE_TIER_LEVEL_PREMIUM_MODEL_USAGE === 'true';
const MAXIMUM_UPSCALE_FACTOR_FOR_PREMIUM_MODEL = +process.env.MAXIMUM_UPSCALE_FACTOR_FOR_PREMIUM_MODEL || 2;
const ENABLE_CHALLENGE_FOOTER = process.env.ENABLE_CHALLENGE_FOOTER === 'true';
const DEFAULT_PUBLIC_STYLE_THUMBNAIL = process.env.DEFAULT_PUBLIC_STYLE_THUMBNAIL || '';
const MAXIMUM_DEFAULT_OUTPUT_COUNT = +process.env.MAXIMUM_DEFAULT_OUTPUT_COUNT || 4;
const PREMIUM_MODEL_DEFAULT_OUTPUT_COUNT = +process.env.PREMIUM_MODEL_DEFAULT_OUTPUT_COUNT || 1;

/** Bounty */
const ENABLE_NEW_BOUNTIES_SORTING = process.env.ENABLE_NEW_BOUNTIES_SORTING === 'true';

/** Challenge */
const CHALLENGE_ENTRY_LIMIT = +process.env.CHALLENGE_ENTRY_LIMIT || 1;

/** Video Generation */
const PIKA_URL = process.env.PIKA_URL || '';
const PIKA_API_KEY = process.env.PIKA_API_KEY || '';
const PIKA_VIDEO_CREDIT_COST = +process.env.PIKA_VIDEO_CREDIT_COST || 20;
const DEFAULT_VIDEO_MODEL_VERSION = process.env.DEFAULT_VIDEO_MODEL_VERSION || '';

/** Album */
const ENABLE_ADD_PRIMARY_ALBUM = process.env.ENABLE_ADD_PRIMARY_ALBUM === 'true';
const ENABLE_ALBUM_SWANLING_TOTAL_REACTS_COUNT = process.env.ENABLE_ALBUM_SWANLING_TOTAL_REACTS_COUNT === 'true';

const ENABLE_NEGATIVE_BALANCE = process.env.ENABLE_NEGATIVE_BALANCE === 'true';

/** Trading 2.0 */
const NUDGE_SPONSORED_INACTIVE_DAYS = +process.env.NUDGE_SPONSORED_INACTIVE_DAYS || 10;
const DELIST_SPONSORED_INACTIVE_DAYS = +process.env.DELIST_SPONSORED_INACTIVE_DAYS || 21;
const REFUND_SPONSOR_INACTIVE_DAYS = +process.env.REFUND_SPONSOR_INACTIVE_DAYS || 30;
const ENABLE_SPONSORED_SWAN_ACTIVITY = process.env.ENABLE_SPONSORED_SWAN_ACTIVITY === 'true';

export {
  REPLICATE_IMAGE_SIZE,
  REPLICATE_AUTH_TOKEN,
  REPLICATE_MODEL_VERSION,
  REPLICATE_CONTROL_NET_VERSION,
  REPLICATE_URL,
  REPLICATE_NEGATIVE_PROMPT,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CREDIT_SYSTEM_SERVICE_BASE_URL,
  GORSE_SERVICE_DOMAIN,
  GORSE_SERVER_API_KEY,
  DREAMBOOTH_AUTH_TOKEN,
  DREAMBOOTH_TRAINING_URL,
  DREAMBOOTH_TRAINER_VERSION,
  DREAMBOOTH_CLASS_PROMPT,
  DREAMBOOTH_WEBHOOK_SECRET,
  DREAMBOOTH_PREDICTION_URL,
  DREAMBOOTH_USERNAME,
  DREAMBOOTH_NEGATIVE_PROMPT,
  DREAMBOOTH_PROMPT_DETAILS,
  DREAMBOOTH_PROMPT_STYLES,
  DREAMBOOTH_PROMPT_CONTENT,
  REPLICATE_WEBHOOK_SECRET,
  ENABLE_BUYBACK_V2,
  ENABLE_BUYBACK_V2_BADGECOUNTER,
  DREAMBOOTH_TRAINING_STEPS_PER_IMAGE,
  DREAMBOOTH_AVATAR_PROMPT,
  DREAMBOOTH_TRAINING_CREDIT_COST,
  MINIMUM_CREDIT_PURCHASE_AMOUNT,
  SPC_TO_CREDIT_CONVERSION_RATE,
  ENABLE_TRENDING_PUBLIC_STYLES,
  TRENDING_STYLES_DAY_COUNT,
  ENABLE_ART_GENERATION_CREDIT_CONSUMPTION,
  PROMPT_GENERATION_CREDIT_COST,
  ENABLE_DAILY_CREDITS,
  DEFAULT_USER_CREDIT_BALANCE,
  ENABLE_DEFAULT_STYLES,
  STYLES_PREVIEW_IMAGE_CACHE_DURATION_IN_SECONDS,
  ENABLE_STYLES_DESCRIPTORS_WEIGHTS,
  ENABLE_PINNED_STYLES,
  DREAMBOOTH_FACE_DETECTION_ENABLED,
  DREAMBOOTH_MODEL_DESTINATION,
  DREAMBOOTH_FINE_TUNE_MODEL_OWNER,
  DREAMBOOTH_FINE_TUNE_MODEL_NAME,
  DREAMBOOTH_FINE_TUNE_MODEL_VERSION,
  DREAMBOOTH_IMAGE_DIMENSIONS,
  DREAMBOOTH_LORA_ENABLED,
  PRIVATE_MODELS_ENABLED,
  ENABLE_ASPECT_RATIO,
  ENABLE_UPDATE_STYLE_WITH_SWANLINGS,
  DEFAULT_STYLE_PREVIEW_IMAGE_URL,
  ENABLE_SWANLING_DISPLAY_SETTINGS,
  REPLICATE_VARIATION_STRONG,
  REPLICATE_VARIATION_SUBTLE,
  REPLICATE_UPSCALE_MODEL_VERSION,
  ENERGY_SYSTEM_ENABLED,
  BASIC_USER_ENERGY_REFILL_GAP_IN_HOURS,
  VERIFIED_USER_ENERGY_REFILL_GAP_IN_HOURS,
  BASIC_USER_ENERGY_REFILL_AMOUNT,
  VERIFIED_USER_ENERGY_REFILL_AMOUNT,
  BASIC_USER_INITIAL_ENERGY,
  VERIFIED_USER_INITIAL_ENERGY,
  BASIC_USER_ENERGY_CAP,
  VERIFIED_USER_ENERGY_CAP,
  ENERGY_COST_PER_SWANLING,
  CHAT_SERVICE_BASE_URL,
  CHAT_SERVICE_CLIENT_ID,
  CHAT_SERVICE_CLIENT_API_KEY,
  ENABLE_REDIS_PUBSUB,
  ONFIDO_TOKEN,
  ONFIDO_URL,
  ONFIDO_WORKFLOW_ID,
  GOOGLE_SHEETS_UPDATE_ENABLED,
  GOOGLE_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  BOUNTY_WINNERS_GOOGLE_SHEET_ID,
  BOUNTY_ENTRIES_GOOGLE_SHEET_ID,
  SUBSCRIBERS_GOOGLE_SHEET_ID,
  OPEN_AI_PROMPT_CREDIT_COST,
  OPEN_AI_API_KEY,
  NOTIFICATION_SERVICE_BASE_URL,
  BASIC_USER_FREE_CREDIT_LIMIT,
  VERIFIED_USER_FREE_CREDIT_LIMIT,
  PREMIUM_MODELS,
  REQUIRED_BOUNTIES_WON,
  REQUIRED_CREATION_VALUE,
  REQUIRED_BOUNTY_RANK,
  REQUIRED_BOUNTY_HOSTED_DATE,
  REQUIRED_LAST_MOMENT_CREATION_DAYS,
  ENABLE_TIER_LEVEL_ART_GENERATION,
  MAXIMUM_ART_GENERATION_REQUESTS_IN_PROGRESS,
  ENABLE_MAX_ART_GENERATION_LIMIT,
  TRANSACTION_QUEUE_ENABLED,
  VERIFIED_ARTIST_INITIAL_ENERGY,
  VERIFIED_ARTIST_ENERGY_CAP,
  VERIFIED_ARTIST_ENERGY_REFILL_GAP_IN_HOURS,
  VERIFIED_ARTIST_ENERGY_REFILL_AMOUNT,
  VERIFIED_COLLECTOR_FREE_CREDIT_LIMIT,
  GPT_4_VISION_PREVIEW_MAX_TOKENS,
  OPEN_AI_IMAGE_VISION_MODEL,
  ENABLE_TRENDING_STYLES_OPTIMIZATION,
  ENABLE_NEW_BOUNTIES_SORTING,
  VERIFIED_COLLECTOR_AESTHETE_INITIAL_ENERGY,
  VERIFIED_COLLECTOR_AESTHETE_ENERGY_CAP,
  VERIFIED_COLLECTOR_AESTHETE_ENERGY_REFILL_GAP_IN_HOURS,
  VERIFIED_COLLECTOR_AESTHETE_ENERGY_REFILL_AMOUNT,
  ENABLE_TIER_LEVEL_PREMIUM_MODEL_USAGE,
  ENABLE_DAILY_SPC,
  MAXIMUM_UPSCALE_FACTOR_FOR_PREMIUM_MODEL,
  USER_SERVICE_BASE_URL,
  TOP_UP_ICON_URL,
  ENABLE_CHALLENGE_FOOTER,
  VERIFIED_ARTIST_FREE_CREDIT_LIMIT,
  UPGRADED_GUEST_USER_CREDIT_AMOUNT,
  SPC_TO_USD_CONVERSION_RATE,
  MIN_SPC_PAYOUT,
  MAX_SPC_PAYOUT,
  PAYOUT_CYCLE_PROCESSING_DATE,
  CHALLENGE_ENTRY_LIMIT,
  VERIFIED_USER_UPGRADE_REWARD,
  PAYOUT_ICON_URL,
  DEFAULT_PUBLIC_STYLE_THUMBNAIL,
  ACHIEVEMENTS_V2_ENABLED,
  MAXIMUM_DEFAULT_OUTPUT_COUNT,
  PREMIUM_MODEL_DEFAULT_OUTPUT_COUNT,
  PIKA_URL,
  PIKA_API_KEY,
  PIKA_VIDEO_CREDIT_COST,
  ACHIEVEMENT_NOTIFICATION_ICON_URL,
  DEFAULT_VIDEO_MODEL_VERSION,
  POPULAR_STYLES_DAY_COUNT,
  ENABLE_SWAN_TRADING,
  SWAN_VALUE_MAXIMUM_THRESHOLD,
  SWAN_VALUE_MINIMUM_THRESHOLD,
  SPLURGE_ART_ID,
  ENABLE_PAYOUT_NOTIFICATION,
  ENABLE_NEGATIVE_BALANCE,
  VERIFIED_USER_BADGE_URL,
  VERIFIED_ARTIST_BADGE_URL,
  VERIFIED_AESTHETE_BADGE_URL,
  VERIFIED_COLLECTOR_BADGE_URL,
  ENABLE_DAILY_SUBSCRIPTION_VALIDATION,
  NUDGE_SPONSORED_INACTIVE_DAYS,
  DELIST_SPONSORED_INACTIVE_DAYS,
  REFUND_SPONSOR_INACTIVE_DAYS,
  ENABLE_SPONSORED_SWAN_ACTIVITY,
  ENABLE_ADD_PRIMARY_ALBUM,
  ENABLE_ALBUM_SWANLING_TOTAL_REACTS_COUNT,
};
